/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package machine

fun main() {
    //Initialize the machine:
    CustomerInterface().run{
        //initialize the machine
        initializeMachine()
        //check the requirements
        checkCupsRequirements()
    }

}
